# This is a basic workflow to help you get started with Actions

name: Micro Lensing group 2


# We could not figure out how to download the datasets from the website to start the process

# Here are the datasets we want to use but could not download;

http://ogle.astrouw.edu.pl/ogle4/ews/2019/blg-0148.html
http://ogle.astrouw.edu.pl/ogle4/ews/2018/blg-0164.html
http://ogle.astrouw.edu.pl/ogle4/ews/2019/blg-1307.html

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import optimize
import sympy

data1 = np.loadtxt('proj1data1.txt')
data2 = np.loadtxt('proj1data2.txt')
data3 = np.loadtxt('proj1data3.txt')
