# This is a basic workflow to help you get started with Actions

name: Micro Lensing group 2


# We could not figure out how to download the datasets from the website to start the process

# Here are the datasets we want to use but could not download;

http://ogle.astrouw.edu.pl/ogle4/ews/2019/blg-0148.html
http://ogle.astrouw.edu.pl/ogle4/ews/2018/blg-0164.html
http://ogle.astrouw.edu.pl/ogle4/ews/2019/blg-0017.html
http://ogle.astrouw.edu.pl/ogle4/ews/2019/blg-1307.html
